apiVersion: batch/v1
kind: Job
metadata:
  namespace: example06
  generateName: enable-alerts-
  labels:
    codefresh.io/cert: enable-job 
  Annotations:
    argocd.argoproj.io/sync-wave: postsync
    argocd.argoproj.io/hook: 30
spec:
  template:
    spec:
      containers:
      - name: dummy-message
        image: alpine
        command:
          - "sleep"
          - "3"
      restartPolicy: Never
  backoffLimit: 2    
